version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build_default:
    docker:
    - image: circleci/python:3.7
    environment:
      COMPILED_IMAGE: us.gcr.io/vcm-ml/fv3gfs-compiled-default:latest
      COMPILED_TAG_NAME: default
      FV3CONFIG_CACHE_DIR: /.fv3config
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run: make build
      # download inputdata
      - restore_cache:
          keys:
            - v1.2-inputdata-{{ checksum "download_inputdata.sh" }}-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bash download_inputdata.sh
      - run: 
          name: "Install Python test dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            pip3 install git+https://github.com/VulcanClimateModeling/fv3config.git
            python3 -m fv3config.download_data
      - save_cache:
          paths:
            - ./fv3gfs-data-docker_2020-01-13.tar.gz
            - ./venv
            - $FV3CONFIG_CACHE_DIR
          key: v1.2-inputdata-{{ checksum "download_inputdata.sh" }}
      # tests
      - run: which python
      - run: which python3
      - run: 
          name: "Run pytest tests"
          command: |
            . venv/bin/activate
            python tests/pytest/download_reference.py gs://vcm-fv3gfs-data/regression_reference
            pytest tests/pytest
  build_32:
    machine:
      docker_layer_caching: true
    environment:
      COMPILED_IMAGE: us.gcr.io/vcm-ml/fv3gfs-compiled-32bit:latest
      COMPILED_TAG_NAME: 32bit
      COMPILE_OPTION: 32BIT=Y
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run: make build
      # download inputdata
      - restore_cache:
          keys:
            - v1.1-inputdata-{{ checksum "download_inputdata.sh" }}
            # fallback to using the latest cache if no exact match is found
            - v1.1-inputdata-
      - run: bash download_inputdata.sh
      - save_cache:
          paths:
            - ./fv3gfs-data-docker_2020-01-13.tar.gz
          key: v1.1-inputdata-{{ checksum "download_inputdata.sh" }}
      # tests
      - run: bash tests/test_output_netcdfs_identical.sh
workflows:
  version: 2
  build:
    jobs:
      - build_default
